language: ruby
rvm:
- 2.1

cache: bundler

branches:
  only:
  - gh-pages     # test the gh-pages branch

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

install:
  - gem install bundler

before_script:
  - npm install -g bower
  - bower install -f

script:
  - bundle install --jobs=3 --retry=3
  - bundle exec jekyll build
